### ISSUE TITLE
Mojave VM starts, then stops

### ISSUE THREAD

**Issue by alizardx** [img2tab/macos-guest-virtualbox#31] opened 2019-01-29 10:33 UTC
ubuntu 16.04
script stops at the Press Enter when the language window is ready 
![macoshang](https://user-images.githubusercontent.com/47114982/51902090-080daf00-236e-11e9-90d7-c7a28bd93297.png)

**Comment by img2tab** [comment] 2019-01-29 10:40
duplicate of [issue 8](https://github.com/img2tab/macos-guest-virtualbox/issues/8)

**Closed by img2tab** 2019-01-29 10:40 UTC
Labels: duplicate
