### ISSUE TITLE
Nothing happens after "installer started" in install script

### ISSUE THREAD

**Issue by natecraddock** [img2tab/macos-guest-virtualbox#27] opened 2019-01-28 14:31 UTC
After the text `Installer started. Please wait for the license prompt to appear at the bottom of the virtual machine terminal, then press enter here. This will accept the license on the virtual machine.` Nothing happens. 
The bash shell in the VM runs the command `cd "/Install macOS Mojave.app/Contents/Resources/"; ./startosinstall --volume "/Volumes/'"${vmname}"'"` and then shows a prompt for a new command. I waited for a long time and nothing seemed to be running. I have tried multiple times.

**Comment by img2tab** [comment] 2019-01-28 14:58
This was likely due to a bad download URL, I have updated the URL. Please use the latest script (0.34) and report if the installation succeeds.

**Comment by natecraddock** [comment] 2019-01-28 16:05
Yes, the updated URL fixed it. Thank you! I did run into an EOF error after that in the script, but I fixed it and submitted a PR.

**Comment by img2tab** [comment] 2019-01-28 18:23
Duplicate of [issue 26](https://github.com/img2tab/macos-guest-virtualbox/issues/26) (bad URL)

**Closed by img2tab** 2019-01-28 18:23 UTC
Labels: bug, duplicate
