### ISSUE TITLE
Configuration error: Querying "UUID" failed (VERR_CFGM_VALUE_NOT_FOUND)

### ISSUE THREAD

**Issue by abonander** [img2tab/macos-guest-virtualbox#14] opened 2019-01-07 12:51 UTC
On Windows 10 running through MSYS2. VirtualBox 5.22 with extension pack installed.

The UUID seems to be generated but the VM fails to start:

```
[preamble]
Press enter to continue, CTRL-C to exit.
Downloading BaseSystem.dmg from swcdn.apple.com
BaseSystem.dmg                   100%[=======================================================>] 462.86M  7.96MB/s    in 66s
Downloaded BaseSystem.dmg. Converting to BaseSystem.img

dmg2img v1.6.6 (c) vu1tur (to@vu1tur.eu.org)

BaseSystem.dmg --> BaseSystem.img


decompressing:
opening partition 0 ...             100.00%  ok
opening partition 1 ...             100.00%  ok
opening partition 2 ...             100.00%  ok
opening partition 3 ...             100.00%  ok
opening partition 4 ...             100.00%  ok
opening partition 5 ...             100.00%  ok
opening partition 6 ...             100.00%  ok
opening partition 7 ...             100.00%  ok

Archive successfully decompressed as BaseSystem.img
Creating Mojave virtual disk images.
Virtual machine 'Mojave' is created and registered.
UUID: 8448dd40-32ad-451e-a681-64cfa09f1e0c
Settings file: 'C:\Users\cyber\VirtualBox VMs\Mojave\Mojave.vbox'
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Medium created. UUID: e29b00c1-a23c-4751-92e1-553ed1564185
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Medium created. UUID: baf166df-c5fd-4447-8472-e589ca2413a5
Waiting for VM "Mojave" to power on...
VBoxManage.exe: error: Configuration error: Querying "UUID" failed (VERR_CFGM_VALUE_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Press enter when the language select screen is ready.
```

Pressing "Enter" on any of the next steps errors with "VM 'Mojave' is not running"

**Comment by yodasodabob** [comment] 2019-01-14 01:00
I have this same exact issue when i try to run it.  Effectively the same output.

**Comment by img2tab** [comment] 2019-01-14 06:08
Does the script successfully create the BaseSystem.vdi, Mojave.vdi, and Install.vdi files? This may be a duplicate of [issue 5](https://github.com/img2tab/macos-guest-virtualbox/issues/5#issuecomment-451073883).

**Comment by abonander** [comment] 2019-01-14 07:44
Yes:
![image](https://user-images.githubusercontent.com/3198595/51100919-29c33f80-178d-11e9-99b6-5c3362eac88f.png)

**Comment by img2tab** [comment] 2019-01-30 10:49
@abonander The error message `VERR_CFGM_VALUE_NOT_FOUND` appears to be associated with configuring a device without a parent node. This could be due to stray keyboard input that broke the script while it was configuring a virtual device or due to existing configuration that is corrupt or not compatible with the macOS VM. `IConsole` appears to be associated with Hyper-V which is also called `VT-x` and `AMD-V`

I _suspect_ (but could be very wrong) that your CPU does not have enough cores to assign to Hyper-V.

Can you confirm that your CPU has at least four logical cores (two physical cores with two hyperthreads each, or four physical cores, or more) and that it supports VT-x or AMD-V?

**Comment by abonander** [comment] 2019-01-30 11:15
I have an i7 7820X, 8 physical/16 logical cores. I don't have Hyper-V enabled, so it shouldn't be getting used. The feature is still actually installed on the machine so it's conceivable that it's trying to configure the VM for Hyper-V and failing. I can try to uninstall the feature and try the script again.

I thought VirtualBox didn't work with Hyper-V at all, though?

**Comment by img2tab** [comment] 2019-01-31 12:50
@abonander There could have been some problem with the script configuring the VM. Can you unregister and delete the VM then run the script from scratch?

**Comment by abonander** [comment] 2019-02-05 22:41
I deleted the VM and also deleted my clone of `macos-guest-virtualbox` and redownloaded it. On the first attempt I got the following:

```
$ ./macos-guest-virtualbox.sh

  One-key semi-automatic installation of macOS On VirtualBox - Mojave 10.14.3
-------------------------------------------------------------------------------

This installer uses only open-source software and original
unmodified Apple binaries.

The installation requires 33.5GB of available storage,
22GB for the virtual machine and 11.5GB for temporary installation files.
Assigning more storage for the virtual machine is recommended for long-term use.

The script checks for dependencies and will prompt to install them if unmet.

For iCloud and iMessage functionality, you will need to provide a valid
Apple serial number. macOS will work without it, but not Apple-connected apps.

Press enter to continue, CTRL-C to exit.
Locally installing dmg2img
Archive:  dmg2img-1.6.6-win32.zip
  inflating: dmg2img.exe
Initializing Mojave virtual machine configuration file.
VBoxManage.exe: error: Could not find a registered machine named 'Mojave'
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
VBoxManage.exe: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2834 of file VBoxManageInfo.cpp
<continues downloading system images but I cancelled it>
```

I re-cloned the repo to get rid of the partially-downloaded artifacts and pressed `y` when it asked if I wanted to delete the existing image. I also now have a MacBook Pro I borrowed from a coworker, and I entered the Serial #, Device Name, and Board ID into the script. 

Having done this I was able to follow the script through to completion and boot into Mojave. I don't know what I did wrong the first time or if it was a transient error, but it's working now so I guess I don't have a problem anymore. I'll let you decide if you want to keep this open for posterity/further investigation.

On a side note, I can open another issue for this, it'd be nice if there was an option in the script to repeat steps. I accidentally screwed up and pressed Enter prematurely at line 526 in the script, causing half of the `find largest drive` command to get cut off and the subsequent steps to fail. It was only mildly inconvenient to retype the command manually (and fortunately the two subsequent commands were entered correctly so all I had to do was arrow-key up to them), but it'd be nice if there was a way for the script to correct for mistakes like this somehow. I have no idea how I'd want that to work though.

**Comment by img2tab** [comment] 2019-02-06 08:06
Thanks, I'll add these as enhancement issues.

**Closed by img2tab** 2019-02-06 08:06 UTC
Labels: bug, help wanted

**Comment by abonander** [comment] 2019-02-06 09:45
I don't know if @yodasodabob is still having problems though.

**Comment by niralivasoya** [comment] 2019-10-15 13:01
On Windows 10, I installed VirtualBox 6.0.12 and having the same issue. i am trying to install macOS on virtual machine but didn't get any success and it gives error:  

> Configuration error: Querying "UUID" failed (VERR_CFGM_VALUE_NOT_FOUND).

Please someone help to solve this out.

**Comment by myspaghetti** [comment] 2019-10-16 08:26
Hi. Can you provide the `VBox.log` from the host?

The virtual machine log `VBox.log` is found in the [VirtualBox VM log directory](https://blogs.oracle.com/scoter/virtualbox-log-files-v2).

**Comment by niralivasoya** [comment] 2019-10-16 14:12
Hi @myspaghetti.! here i have attached VBox.log file. Please help me to solve this out. I was configuring macOS on windows 10  but still it gives me same error.

[VBox.log](https://github.com/myspaghetti/macos-guest-virtualbox/files/3734771/VBox.log)

**Comment by myspaghetti** [comment] 2019-10-17 00:37
@niralivasoya according to the log you are not using this script but some third-party disk image.

**Comment by niralivasoya** [comment] 2019-10-17 03:28
Hi @myspaghetti, i followed all the steps given in [https://www.wikigain.com/install-macos-sierra-10-12-virtualbox/](url)
to install macOS Sierra on my windows 10, Is it okay or do i need to do some extra steps. please let me know. 

Thanks

**Comment by myspaghetti** [comment] 2019-10-17 09:22
This is an issue tracker for the script, not a general discussion forum.

**Comment by grahamyesfit** [comment] 2019-10-18 18:32
@myspaghetti , I'm getting the same error, and I've attached the log file.

I'm on Windows 10, running through Cygwin.  I have VirtualBox `6.0.14` with the extension pack installed.

I tried deleting the VM and associated files and running the script again, with no luck. One thing I noticed is the parameters of the created VM look a little off and don't match the settings in the script. For example, I have this setting: `cpucount=4` - but the resulting VM has only 1 CPU. I manually adjusted these settings in VirtualBox, but the VM still won't boot up.

Huge thanks in advance if you can take a look.

[VBox.log](https://github.com/myspaghetti/macos-guest-virtualbox/files/3745208/VBox.log)

**Comment by danielehrhardt** [comment] 2020-12-10 18:14
> @myspaghetti , I'm getting the same error, and I've attached the log file.
> 
> I'm on Windows 10, running through Cygwin. I have VirtualBox `6.0.14` with the extension pack installed.
> 
> I tried deleting the VM and associated files and running the script again, with no luck. One thing I noticed is the parameters of the created VM look a little off and don't match the settings in the script. For example, I have this setting: `cpucount=4` - but the resulting VM has only 1 CPU. I manually adjusted these settings in VirtualBox, but the VM still won't boot up.
> 
> Huge thanks in advance if you can take a look.
> 
> [VBox.log](https://github.com/myspaghetti/macos-guest-virtualbox/files/3745208/VBox.log)
> 
> Edit: I ran the script with the vm_configure option, and now the VM boots. I'm not sure what happened there, but it looks like I'm up and running. Thanks for an awesome utility, this has saved me several days of pain.
> 
> Edit 2: I've almost finished process and I have to say, this script is absolutely incredible. Huge kudos to @myspaghetti for making this available to us. I'm a Windows guy so it's been extra helpful for me. I'd give you a thousands stars if I could.

Are you able to make it work?
