### ISSUE TITLE
WSL gets the paths wrong.

### ISSUE THREAD

**Issue by rabievdm** [img2tab/macos-guest-virtualbox#41] opened 2019-03-08 07:18 UTC
I'm trying to run this on WSL but by the looks of it because the file locations are all relative it's getting the locations wrong between the WSL commands and Windows native commands.
eg I'm on a WSL shell and I execute the shell script there which would be /home/rabie/macos (I placed the script there.
The wget works and dumps the BaseSystem.dmg in /home/rabie/macos and the convert to .img works, but then when VBoxManage.exe (and all related Windows native commands) gets called it defaults to c:\Windows\System32 as it's working directory. It then looks for all the IMG and VDI files there which then failes.

A solution would be to specify a working directory eg "/mnt/c/temp/" and "c:\temp" and then prepend all relevant file operations with those paths or (less than ideal nor not sure how this would be possible) to change directory prior to calling the exes)
If I manage to, I'll try and fix and upload the script.

Herewith the failed messages:

Press enter to continue, CTRL-C to exit.
VBoxManage.exe: error: Could not find a registered machine named 'MacOsMojave'
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
VBoxManage.exe: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2621 of file VBoxManageInfo.cpp
Downloading BaseSystem.dmg from swcdn.apple.com
--2019-03-08 08:20:39--  http://swcdn.apple.com/content/downloads/34/52/041-38914/dhgsi49xaudtqpbj3zibbmjy3ry9ola2rb/BaseSystem.dmg
Resolving swcdn.apple.com (swcdn.apple.com)... 197.80.131.145, 197.80.131.146
Connecting to swcdn.apple.com (swcdn.apple.com)|197.80.131.145|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 485306481 (463M), 478478818 (456M) remaining [application/octet-stream]
Saving to: ‘BaseSystem.dmg’

BaseSystem.dmg                            100%[+=================================================================================>] 462.82M  1.25MB/s    in 6m 38s

2019-03-08 08:27:19 (1.15 MB/s) - ‘BaseSystem.dmg’ saved [485306481/485306481]

Downloaded BaseSystem.dmg. Converting to BaseSystem.img

dmg2img v1.6.7 (c) vu1tur (to@vu1tur.eu.org)

BaseSystem.dmg --> BaseSystem.img

decompressing:
opening partition 0 ...             100.00%  ok
opening partition 1 ...             100.00%  ok
opening partition 2 ...             100.00%  ok
opening partition 3 ...             100.00%  ok
opening partition 4 ...             100.00%  ok
opening partition 5 ...             100.00%  ok
opening partition 6 ...             100.00%  ok
opening partition 7 ...             100.00%  ok

Archive successfully decompressed as BaseSystem.img
Converting from raw image file="BaseSystem.img" to file="BaseSystem.vdi"...
VBoxManage.exe: error: Cannot open file "BaseSystem.img": VERR_FILE_NOT_FOUND
Creating MacOsMojave target system virtual disk image.
0%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage.exe: error: Failed to create medium
VBoxManage.exe: error: Could not create the medium storage unit 'C:\Windows\system32\MacOsMojave.vdi'.
VBoxManage.exe: error: VDI: cannot create image 'C:\Windows\system32\MacOsMojave.vdi' (VERR_ACCESS_DENIED)
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MediumWrap, interface IMedium
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreateMedium(struct HandlerArg *)" at line 462 of file VBoxManageDisk.cpp
Creating MacOsMojave installation media virtual disk image.
Oracle VM VirtualBox Command Line Management Interface Version 6.0.4
(C) 2005-2019 Oracle Corporation
All rights reserved.

Usage:

VBoxManage createmedium     [disk|dvd|floppy] --filename <filename>
                            [--size <megabytes>|--sizebyte <bytes>]
                            [--diffparent <uuid>|<filename>
                            [--format VDI|VMDK|VHD] (default: VDI)
                            [--variant Standard,Fixed,Split2G,Stream,ESX,
                                       Formatted]

Syntax error: Invalid parameter 'MacOsMojave.vdi'
VBoxManage.exe: error: Could not find file for the medium 'C:\Windows\system32\MacOsMojave.vdi' (VERR_FILE_NOT_FOUND)
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MediumWrap, interface IMedium, callee IUnknown
VBoxManage.exe: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 191 of file VBoxManageDisk.cpp
VBoxManage.exe: error: Invalid UUID or filename "MacOsMojave.vdi"
Oracle VM VirtualBox Command Line Management Interface Version 6.0.4
(C) 2005-2019 Oracle Corporation
All rights reserved.

Usage:

VBoxManage storageattach    <uuid|vmname>
                            --storagectl <name>
                            [--port <number>]
                            [--device <number>]
                            [--type dvddrive|hdd|fdd]
                            [--medium none|emptydrive|additions|
                                      <uuid|filename>|host:<drive>|iscsi]
                            [--mtype normal|writethrough|immutable|shareable|
                                     readonly|multiattach]
                            [--comment <text>]
                            [--setuuid <uuid>]
                            [--setparentuuid <uuid>]
                            [--passthrough on|off]
                            [--tempeject on|off]
                            [--nonrotational on|off]
                            [--discard on|off]
                            [--hotpluggable on|off]
                            [--bandwidthgroup <name>]
                            [--forceunmount]
                            [--server <name>|<ip>]
                            [--target <target>]
                            [--tport <port>]
                            [--lun <lun>]
                            [--encodedlun <lun>]
                            [--username <username>]
                            [--password <password>]
                            [--passwordfile <file>]
                            [--initiator <initiator>]
                            [--intnet]

VBoxManage.exe: error: Invalid parameter 'MacOsMojave.vdi'
VBoxManage.exe: error: Could not find file for the medium 'C:\Windows\system32\BaseSystem.vdi' (VERR_FILE_NOT_FOUND)
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MediumWrap, interface IMedium, callee IUnknown
VBoxManage.exe: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 191 of file VBoxManageDisk.cpp
VBoxManage.exe: error: Invalid UUID or filename "BaseSystem.vdi"
Starting virtualmachine MacOsMojave. This should take a couple of minutes.
Waiting for VM "MacOsMojave" to power on...
VM "MacOsMojave" has been successfully started.

**Comment by img2tab** [comment] 2019-03-09 02:43
First, congrats for the most thorough bug report yet. Second, serves me right for trusting this works on WSL without verifying.

Thanks for the report, I guess it's time for me to install WSL and actually test the script there.

**Comment by img2tab** [comment] 2019-03-09 04:01
@rabievdm I haven't installed WSL yet but if you could update to version 0.46 and check that the following commands create the VDIs successfully:

`macos-guest-virtualbox.sh create_vm  create_basesystem_vdi create_target_vdi create_install_vdi attach_initial_storage`

VBoxManage should be well-behaved on WSL now.

**Comment by img2tab** [comment] 2019-03-09 04:24
@rabievdm, as with https://github.com/img2tab/macos-guest-virtualbox/issues/41, please make sure you are running the script with Bash version 4.0 or higher. Translating WSL paths to Windows paths requires (for some obscene reason) PHP, which is a dependency I don't want to add to the script.

**Comment by rabievdm** [comment] 2019-03-09 07:49
Hi,

I'm on bash 4.4 and no php:
rabie@DESKTOP-KFL1A3N:~/macos$ dpkg -l | grep -i php
dpkg -l | grep -i php
rabie@DESKTOP-KFL1A3N:~/macos$

I have managed to work around the path issue by creating 2 variables (linpath and winpath) and then prepending every instance with said variables.
It's a bit of a hack job, current issues with that is it refers to a temp location and I have yet to work out how to get the 'default' VM store location, in other words all my VM's disk images are currently going to the temp directory and not stored with the VM itself because if I dont add the path then it tries to default to c:\windows\system32.

**Comment by rabievdm** [comment] 2019-03-09 14:28
I've made a progress!!! :)
Moving the "declare -A key" array declaration out into the may body of the script (ie making it a global array instead of a local array) the scancodes now work.
Found one more issue, for reason it looks like 2 x ENTERS is required to get past the main Language screen. So I've amended the script to do that.
Busy completing the install.
If that works then I'll submit my hacked script for the maintainer to cherry pick :)

I also see that it's possible to retrieve the default VM location so we could in theory then place the new vdi's in the same folder as my current path hack just drops them into a common temp folder.
On windows cmdline 'vboxmanage list systemproperties | find "folder"'
On wsl/cygwin cmdline 'vboxmanage list systemproperties | grep "folder"'

**Comment by rabievdm** [comment] 2019-03-09 16:34
I have uploaded a modified script that works on WSL and sets paths. I have uploaded it as a new script which the maintainer can scrutinize and cherrypick that they want also because I don't have rights to upload to the existing script :)
The only todo would be to move the final vdi file to it's proper location.

**Comment by img2tab** [comment] 2019-03-09 18:06
@rabievdm There's got to be a better way than using absolute paths.

**Comment by rabievdm** [comment] 2019-03-09 18:11
Agreed, using the 'vboxmanage list systemproperties | find folder' would be the way to go, but I'm afraid my bash skills are fairly limited :)
You could use that to find the default VM store location then use that as a basis, but I would leave that to the experts.

**Comment by img2tab** [comment] 2019-03-09 18:12
`vboxmanage list systemproperties` does appear to be the way to go. Thanks!

**Comment by img2tab** [comment] 2019-03-09 20:04
WSL should actually work on version 0.50. _Not tested_, but should work...

**Comment by img2tab** [comment] 2019-03-29 18:21
Tested, works.

**Comment by mpkossen** [comment] 2019-03-30 13:41
I just tested this with both master and 0.53 on WSL with bash>4.0 and no php and I still get this error. It defaults to C:\Windows\system32 to find the .img files, while they are in the home folder of WSL.

It seems wsl_home is set to C:\Windows\system32 when running the script, as 'cmd C/ cd' takes you there.

I haven't been able to distill @rabievdm's solution from this post, but I assume setting wsl_home to a directory that is accessible and contains the right files solves the issue. I'll do some tests when I can.

**Comment by rabievdm-apx** [comment] 2019-03-30 13:47
@mpkossen My hack was to create some variables and set the relevant paths and then find each instance where a file was referenced and then prepend the variable depending on if it was a 'dos' path or a 'linux' path. Should be called brutal hack, but it wasnt a proper fix. :)

**Comment by mpkossen** [comment] 2019-03-30 16:36
Setting wsl_home to the _actual_ wsl_home as accessible from Windows does the trick. The script sets it to "" and then to C:\Windows\system32, which breaks it. I think the assumption is that wsl_home should be set and making it a configurable variable would do the trick.

The actual WSL home is something like:

`C:/Users/username/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_xxxxxxxxxxxxx/LocalState/rootfs/home/username/`

I just tested this and the script seems to work correctly. 

From what I remember paths and WSL are a tricky thing in general. In the past you were not able to create files on the WSL filesystem from Windows, but it did work the other way around as there's a Windows mount inside WSL. Not sure if that's still the case right now, but that might affect how things work.

Also, but this may be a different topic entirely, the main vdi for this VM is created outside the directory which contains the other VirtualBox files. It's not that hard to move it of course, but since it ties into this I thought I'd mention it.

**Comment by img2tab** [comment] 2019-03-31 04:06
`wsl_home` will set the path to your Windows (not WSL) home directory if you don't run the script with elevated privileges, which you shouldn't be doing. I'll name the variable "windows_home" to make it clearer that it's not the WSL user's home directory.

The script is supposed to work in a single working directory. Ideally it'd translate WSL paths into Windows paths, but this requires PHP, which I am not willing to accept as a dependency for _translating paths_. I use `cmd /C cd` to get the Windows user's home path, but if the script is run with elevated privileges it returns the Windows system32 path.

**Comment by img2tab** [comment] 2019-03-31 05:13
`wsl_home` will set the path to the script working directory if you don't run the script with elevated privileges, which you shouldn't be doing. I'll name the variable "windows_path" to make it clearer that it's not the WSL user's home directory.

The script is supposed to work in a single working directory. Ideally it'd translate WSL paths into Windows paths, but this requires PHP, which I am not willing to accept as a dependency for _translating paths_. I use `cmd /C cd` to get the script's working directory, but if the script is executed from the Windows GUI with elevated privileges the working directory is the Windows system32 path.

**Comment by mpkossen** [comment] 2019-04-06 07:20
On a non-elevated Bash on Windows prompt:

`mpkossen@mpkossen:~$ echo $(cmd.exe /C cd)
C:\Windows\system32`

Could it be my system that gets this wrong? The way I understand you intend this to work is for this command to return the user's home directory (eg. C:\Users\JohnDoe) to which the script should have access.

**Comment by mpkossen** [comment] 2019-04-06 07:32
I did a little bit of research. This command works for me to get the Windows path for the Windows user's home directory:

`$(cmd.exe /c "<nul set /p=%UserProfile%" 2>/dev/null)`

However, 'wslpath' is now part of WSL, which should be able to translate paths without requiring PHP. Having said that, using wslpath, this command returns the path of the Windows home directory within WSL (eg. /mnt/c/Users/mpkossen):

`$(wslpath $(cmd.exe /C "echo %USERPROFILE%"))`

Which is what I think you wanted in the first place.

Source: https://superuser.com/questions/1271205/how-to-get-the-host-user-home-directory-in-wsl-bash

**Comment by img2tab** [comment] 2019-04-07 20:10
I can't reproduce the WSL issue with `cmd.exe /c cd` returning `C:\Windows\System32` for non-elevated-privileges `cmd.exe`, but regardless the script needs a solution for VBoxManage that works with paths with spaces too.

**Comment by img2tab** [comment] 2019-05-12 10:16
Fixed in version 0.61 with `cmd /d /s /c call "${absolute_path_VBoxManage}" "$@"`

**Closed by img2tab** 2019-05-12 10:16 UTC
Labels: bug
