### ISSUE TITLE
VM fails to start after moving installation files to the virtual disk

### ISSUE THREAD

**Issue by aroper23** [img2tab/macos-guest-virtualbox#36] opened 2019-02-09 23:51 UTC
The VM setup makes it to the reboot in the step with the comment `# reboot, because the installer does not work when the partition is remounted`, but then the VM crashes when starting with this error.

> The instruction at 0x0007F9E97884AC0 referenced memory at 0x00000000000000000010. The memory could not be used.

Also, there appears to be some sort of limit imposed by Apple for how many files you can download in a certain timeframe from swcdn.apple.com. I had to manually issue curl commands to download some of the files in the `downloading macOS` step.

**Comment by Phiplex** [comment] 2019-02-10 08:35
Ii have had the same type of crash, at another instruction location but referencing the same memory location 0x00000000000000000010. This occur from time to time, but not always, trying to start the VM. 

If I than keep trying to start the VM,, sometimes maybe up till 10 times, but normally just one or two times the VM will start.

**Comment by img2tab** [comment] 2019-02-10 12:00
>Also, there appears to be some sort of limit imposed by Apple for how many files you can download in a certain timeframe from swcdn.apple.com. I had to manually issue curl commands to download some of the files in the `downloading macOS` step.

Hammering swcdn.apple.com at 10 http requests per second, I could not reproduce the rate-limiting effect.

>The memory could not be used.

Could not reproduce. Since this bug is intermittent I assume it's with VirtualBox itself and not the script. It might be solved through some machine-specific configuration like [issue 8 (stuck on End RandomSeed)](https://github.com/img2tab/macos-guest-virtualbox/issues/8).

**Comment by aroper23** [comment] 2019-02-10 16:06
You're correct about restarting the VM a few times before the memory issue was bypassed.

When I encountered the download issue, instead of receiving the expected content the file contained 404 html. I waited half an hour to allow for whatever restriction was imposed to elapse, and was then able to download the next file using curl.

**Comment by img2tab** [comment] 2019-02-28 06:23
Closing: could not reproduce server rate-limit; boot issue unrelated to script config or execution.

**Closed by img2tab** 2019-02-28 06:23 UTC
Labels: bug
