### ISSUE TITLE
VDI isn't created automatically

### ISSUE THREAD

**Issue by Dev0110** [img2tab/macos-guest-virtualbox#43] opened 2019-03-09 17:21 UTC
The VDI "Install Mojave" isn't created, I have to do it manually and to attach it too.
Windows 10 with WSL

`Downloading BaseSystem.dmg from swcdn.apple.com
--2019-03-09 18:07:35--  http://swcdn.apple.com/content/downloads/34/52/041-38914/dhgsi49xaudtqpbj3zibbmjy3ry9ola2rb/BaseSystem.dmg
Resolving swcdn.apple.com (swcdn.apple.com)... 17.253.109.203, 17.253.109.202
Connecting to swcdn.apple.com (swcdn.apple.com)|17.253.109.203|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 485306481 (463M) [application/octet-stream]
Saving to: 'BaseSystem.dmg'

BaseSystem.dmg                100%[=================================================>] 462.82M  2.86MB/s    in 97s

2019-03-09 18:09:12 (4.78 MB/s) - 'BaseSystem.dmg' saved [485306481/485306481]

Downloaded BaseSystem.dmg. Converting to BaseSystem.img

dmg2img v1.6.5 (c) vu1tur (to@vu1tur.eu.org)

BaseSystem.dmg --> BaseSystem.img

decompressing:
opening partition 0 ...             100.00%  ok
opening partition 1 ...             100.00%  ok
opening partition 2 ...             100.00%  ok
opening partition 3 ...             100.00%  ok
opening partition 4 ...             100.00%  ok
opening partition 5 ...             100.00%  ok
opening partition 6 ...             100.00%  ok
opening partition 7 ...             100.00%  ok

Archive successfully decompressed as BaseSystem.img
Converting from raw image file="BaseSystem.img" to file="BaseSystem.vdi"...
Creating dynamic image with size 2146541568 bytes (2048MB)...
Creating MacOS target system virtual disk image.
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Medium created. UUID: ebe9ac1c-90bf-4e21-a086-dc114e5284ac
Creating MacOS installation media virtual disk image.
Oracle VM VirtualBox Command Line Management Interface Version 6.0.4
(C) 2005-2019 Oracle Corporation
All rights reserved.

Usage:

VBoxManage createmedium     [disk|dvd|floppy] --filename <filename>
                            [--size <megabytes>|--sizebyte <bytes>]
                            [--diffparent <uuid>|<filename>
                            [--format VDI|VMDK|VHD] (default: VDI)
                            [--variant Standard,Fixed,Split2G,Stream,ESX,
                                       Formatted]

Syntax error: Invalid parameter 'MacOS.vdi'
Oracle VM VirtualBox Command Line Management Interface Version 6.0.4
(C) 2005-2019 Oracle Corporation
All rights reserved.

Usage:

VBoxManage storageattach    <uuid|vmname>
                            --storagectl <name>
                            [--port <number>]
                            [--device <number>]
                            [--type dvddrive|hdd|fdd]
                            [--medium none|emptydrive|additions|
                                      <uuid|filename>|host:<drive>|iscsi]
                            [--mtype normal|writethrough|immutable|shareable|
                                     readonly|multiattach]
                            [--comment <text>]
                            [--setuuid <uuid>]
                            [--setparentuuid <uuid>]
                            [--passthrough on|off]
                            [--tempeject on|off]
                            [--nonrotational on|off]
                            [--discard on|off]
                            [--hotpluggable on|off]
                            [--bandwidthgroup <name>]
                            [--forceunmount]
                            [--server <name>|<ip>]
                            [--target <target>]
                            [--tport <port>]
                            [--lun <lun>]
                            [--encodedlun <lun>]
                            [--username <username>]
                            [--password <password>]
                            [--passwordfile <file>]
                            [--initiator <initiator>]
                            [--intnet]

VBoxManage.exe: error: Invalid parameter 'MacOS.vdi'
Starting virtualmachine MacOS. This should take a couple of minutes.
Waiting for VM "MacOS" to power on...
VM "MacOS" has been successfully started.`

**Comment by img2tab** [comment] 2019-03-09 18:04
Duplicate of #41 .

**Closed by img2tab** 2019-03-09 18:04 UTC
Labels: duplicate
